package com.suse.blog_cy.dao;

import com.suse.blog_cy.bean.JdbcTest;
import com.suse.blog_cy.bean.JdbcTestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JdbcTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdbc_test
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    long countByExample(JdbcTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdbc_test
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    int deleteByExample(JdbcTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdbc_test
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    int insert(JdbcTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdbc_test
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    int insertSelective(JdbcTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdbc_test
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    List<JdbcTest> selectByExample(JdbcTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdbc_test
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    int updateByExampleSelective(@Param("record") JdbcTest record, @Param("example") JdbcTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdbc_test
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    int updateByExample(@Param("record") JdbcTest record, @Param("example") JdbcTestExample example);
}