package com.suse.blog_cy.dao;

import com.suse.blog_cy.bean.TbBlog;
import com.suse.blog_cy.bean.TbBlogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbBlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    long countByExample(TbBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    int deleteByExample(TbBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    int deleteByPrimaryKey(Long blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    int insert(TbBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    int insertSelective(TbBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    List<TbBlog> selectByExampleWithBLOBs(TbBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    List<TbBlog> selectByExample(TbBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    TbBlog selectByPrimaryKey(Long blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    int updateByExampleSelective(@Param("record") TbBlog record, @Param("example") TbBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") TbBlog record, @Param("example") TbBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    int updateByExample(@Param("record") TbBlog record, @Param("example") TbBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    int updateByPrimaryKeySelective(TbBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(TbBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    int updateByPrimaryKey(TbBlog record);
}