package com.suse.blog_cy.bean;

public class JdbcTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdbc_test.type
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdbc_test.name
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdbc_test.type
     *
     * @return the value of jdbc_test.type
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdbc_test.type
     *
     * @param type the value for jdbc_test.type
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdbc_test.name
     *
     * @return the value of jdbc_test.name
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdbc_test.name
     *
     * @param name the value for jdbc_test.name
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}