package com.suse.blog_cy.bean;

import java.util.Date;

public class TbBlog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_id
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    private Long blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_title
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    private String blogTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_sub_url
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    private String blogSubUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_cover_image
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    private String blogCoverImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_category_id
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    private Integer blogCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_category_name
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    private String blogCategoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_tags
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    private String blogTags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_status
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    private Byte blogStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_views
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    private Long blogViews;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.enable_comment
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    private Byte enableComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.is_deleted
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.create_time
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.update_time
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_content
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    private String blogContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_id
     *
     * @return the value of tb_blog.blog_id
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_id
     *
     * @param blogId the value for tb_blog.blog_id
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_title
     *
     * @return the value of tb_blog.blog_title
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public String getBlogTitle() {
        return blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_title
     *
     * @param blogTitle the value for tb_blog.blog_title
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle == null ? null : blogTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_sub_url
     *
     * @return the value of tb_blog.blog_sub_url
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public String getBlogSubUrl() {
        return blogSubUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_sub_url
     *
     * @param blogSubUrl the value for tb_blog.blog_sub_url
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public void setBlogSubUrl(String blogSubUrl) {
        this.blogSubUrl = blogSubUrl == null ? null : blogSubUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_cover_image
     *
     * @return the value of tb_blog.blog_cover_image
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public String getBlogCoverImage() {
        return blogCoverImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_cover_image
     *
     * @param blogCoverImage the value for tb_blog.blog_cover_image
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public void setBlogCoverImage(String blogCoverImage) {
        this.blogCoverImage = blogCoverImage == null ? null : blogCoverImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_category_id
     *
     * @return the value of tb_blog.blog_category_id
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public Integer getBlogCategoryId() {
        return blogCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_category_id
     *
     * @param blogCategoryId the value for tb_blog.blog_category_id
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public void setBlogCategoryId(Integer blogCategoryId) {
        this.blogCategoryId = blogCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_category_name
     *
     * @return the value of tb_blog.blog_category_name
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public String getBlogCategoryName() {
        return blogCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_category_name
     *
     * @param blogCategoryName the value for tb_blog.blog_category_name
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public void setBlogCategoryName(String blogCategoryName) {
        this.blogCategoryName = blogCategoryName == null ? null : blogCategoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_tags
     *
     * @return the value of tb_blog.blog_tags
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public String getBlogTags() {
        return blogTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_tags
     *
     * @param blogTags the value for tb_blog.blog_tags
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public void setBlogTags(String blogTags) {
        this.blogTags = blogTags == null ? null : blogTags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_status
     *
     * @return the value of tb_blog.blog_status
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public Byte getBlogStatus() {
        return blogStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_status
     *
     * @param blogStatus the value for tb_blog.blog_status
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public void setBlogStatus(Byte blogStatus) {
        this.blogStatus = blogStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_views
     *
     * @return the value of tb_blog.blog_views
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public Long getBlogViews() {
        return blogViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_views
     *
     * @param blogViews the value for tb_blog.blog_views
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public void setBlogViews(Long blogViews) {
        this.blogViews = blogViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.enable_comment
     *
     * @return the value of tb_blog.enable_comment
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public Byte getEnableComment() {
        return enableComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.enable_comment
     *
     * @param enableComment the value for tb_blog.enable_comment
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public void setEnableComment(Byte enableComment) {
        this.enableComment = enableComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.is_deleted
     *
     * @return the value of tb_blog.is_deleted
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.is_deleted
     *
     * @param isDeleted the value for tb_blog.is_deleted
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.create_time
     *
     * @return the value of tb_blog.create_time
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.create_time
     *
     * @param createTime the value for tb_blog.create_time
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.update_time
     *
     * @return the value of tb_blog.update_time
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.update_time
     *
     * @param updateTime the value for tb_blog.update_time
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_content
     *
     * @return the value of tb_blog.blog_content
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public String getBlogContent() {
        return blogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_content
     *
     * @param blogContent the value for tb_blog.blog_content
     *
     * @mbg.generated Fri Dec 17 18:17:03 CST 2021
     */
    public void setBlogContent(String blogContent) {
        this.blogContent = blogContent == null ? null : blogContent.trim();
    }
}